apiVersion: apps/v1
kind: Deployment
metadata:
  name: rincewind
  labels:
    app: rincewind
spec:
  selector:
    matchLabels:
      app: rincewind
  replicas: 3
  template:
    metadata:
      labels:
        app: rincewind
    spec:
      containers:
      - name: rincewind
        image: dsinnovators/training:rincewind
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: rincewind
  labels:
    app: rincewind
    name: rincewind
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30002
  selector:
    app: rincewind
